name: ori-reaper
version: 0.0.7
description: REAPER DAW integration - manage scripts, actions, and workflows for music production
license: MIT
repository: https://github.com/johnjallday/ori-reaper

maintainers:
  - name: Ori Agent Team
    email: noreply@ori-agent.dev

platforms:
  - os: darwin
    architectures: [amd64, arm64]

requirements:
  min_ori_version: "0.0.9"
  dependencies: []
